"""Sync merged domain ratings dataset into Cloudflare D1 via wrangler."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile


def _chunks(items: list[dict], size: int) -> list[list[dict]]:
    return [items[i : i + size] for i in range(0, len(items), size)]


def _sql_escape(value: str) -> str:
    return value.replace("'", "''")


def _record_to_sql_tuple(record: dict) -> str:
    naming = record.get("naming_format", {})
    values = [
        _sql_escape(record["domain"]),
        _sql_escape(record["verdict"]),
        str(int(record["confidence"])),
        str(int(record["evidence_count"])),
        _sql_escape(json.dumps(record["result_counts"], separators=(",", ":"))),
        _sql_escape(json.dumps(record["raw_result_counts"], separators=(",", ":"))),
        _sql_escape(json.dumps(record["provider_schema_counts"], separators=(",", ":"))),
        "1" if record["has_free_provider_evidence"] else "0",
        "1" if record["has_role_evidence"] else "0",
        _sql_escape(naming.get("primary_format_label", "unknown")),
        str(int(naming.get("primary_format_confidence", 0))),
        _sql_escape(json.dumps(naming.get("format_distribution", []), separators=(",", ":"))),
        _sql_escape(json.dumps(naming.get("raw_naming_format_codes", {}), separators=(",", ":"))),
        _sql_escape(record["aggregated_at"]),
        _sql_escape(record.get("source", "historical-merged")),
    ]
    return "('" + "','".join(values) + "')"


def _build_insert_sql(chunk: list[dict]) -> str:
    rows = ",\n".join(_record_to_sql_tuple(record) for record in chunk)
    return (
        "INSERT OR REPLACE INTO domain_ratings ("
        "domain, verdict, confidence, evidence_count, result_counts_json, "
        "raw_result_counts_json, provider_schema_counts_json, has_free_provider_evidence, "
        "has_role_evidence, naming_format_primary_label, naming_format_primary_confidence, "
        "naming_format_distribution_json, raw_naming_format_codes_json, aggregated_at, source"
        ")\nVALUES\n"
        f"{rows};\n"
    )


def _run(command: list[str], cwd: Path) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Load merged domain ratings JSONL into Cloudflare D1."
    )
    parser.add_argument(
        "--database",
        required=True,
        help="D1 database binding/name to pass to `wrangler d1 execute`.",
    )
    parser.add_argument(
        "--input-jsonl",
        default="millionverifierlists/derived/domain_ratings.jsonl",
        help="JSONL file generated by build_domain_ratings_dataset.py.",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=500,
        help="Rows per INSERT batch (default: 500).",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="Execute against remote D1 (adds --remote).",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    schema_path = repo_root / "sql" / "d1_domain_ratings_schema.sql"
    input_path = (repo_root / args.input_jsonl).resolve()

    wrangler_bin = shutil.which("wrangler") or shutil.which("wrangler.cmd")
    if not wrangler_bin:
        raise RuntimeError("`wrangler` CLI not found in PATH.")
    if not schema_path.exists():
        raise FileNotFoundError(f"Schema file not found: {schema_path}")
    if not input_path.exists():
        raise FileNotFoundError(f"Input dataset not found: {input_path}")

    records: list[dict] = []
    for line in input_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        records.append(json.loads(line))
    if not records:
        raise RuntimeError("No domain rating records found in input JSONL.")

    batches = _chunks(records, args.chunk_size)
    base = [wrangler_bin, "d1", "execute", args.database]
    if args.remote:
        base.append("--remote")

    _run([*base, f"--file={schema_path}"], cwd=repo_root)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        for index, batch in enumerate(batches, start=1):
            sql_file = tmp_dir / f"import_{index:05d}.sql"
            sql_file.write_text(_build_insert_sql(chunk=batch), encoding="utf-8")
            _run([*base, f"--file={sql_file}"], cwd=repo_root)
            print(f"Imported batch {index}/{len(batches)} ({len(batch)} rows)")

    print(f"Completed D1 sync: {len(records)} domain rating rows.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
